### ISSUE TITLE
Compability w/ current version of anki

### ISSUE THREAD

**Issue by phu54321** [trgkanki/addon_backup#1]
Addon is incompatible w/ current anki version. Currently addon uses following code to download missing addons. (See https://github.com/trgkanki/addon_backup/blob/5c8ada8850f852e7b22311582fbacc35a61a6aca/src/unpack.py#L74)

```py
        # Install missing addons
        for addonID, metadata in addonBackupConfig['addons'].items():
            if addonID not in installedAddonIDs:
                askSettingChange()
                _, errs = mw.addonManager.downloadIds([addonID])
                if errs:
                    showInfo('Download of addon %s failed. Check internet connection' % addonID)
                    askNoUpload()
                    continue
```

`AddonManager::downlaodIds` have been removed since https://github.com/ankitects/anki/commit/6134ae9ec6f8ddb590065c0773eb0edb337d64d2. Code should now use `download_addons` instead.

**Comment by phu54321** [comment]
bump

**Comment by adelin-b** [comment]
Still an issue.
